2025-01-05 20:16:44,617 WARNING Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\kan_o\PycharmProjects\module_12\module_12_4_logging.py", line 72, in test_run
    self.TestRunner = Runner(124)
                      ^^^^^^^^^^^
  File "C:\Users\kan_o\PycharmProjects\module_12\module_12_4_logging.py", line 11, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2025-01-05 20:16:44,618 WARNING Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\kan_o\PycharmProjects\module_12\module_12_4_logging.py", line 61, in test_wolk
    self.TestRunner = Runner('test_runner', speed=-5)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kan_o\PycharmProjects\module_12\module_12_4_logging.py", line 16, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
